const DEFAULT_ROW_COUNT = 3;
const DEFAULT_COL_COUNT = 5;
const DEFAULT_ROW_SIZE = 30;
const DEFAULT_COL_SIZE = 100;

export { DEFAULT_COL_COUNT, DEFAULT_ROW_COUNT, DEFAULT_COL_SIZE, DEFAULT_ROW_SIZE };
